server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/sklep}
      database: ${MONGODB_DATABASE:sklep}
      auto-index-creation: false
  
  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:5173}
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  security:
    basic:
      enabled: false

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation2024EcommerceApplication}
    expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
  
  security:
    rate-limit:
      requests: ${RATE_LIMIT_REQUESTS:100}
      window: ${RATE_LIMIT_WINDOW:3600000}  # 1 hour in milliseconds
  
  upload:
    directory: ${UPLOAD_DIRECTORY:uploads/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: false

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.ecommerce: INFO
    org.mongodb.driver: WARN
