server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://dwaf:szPt2RsSrsmZdDHl@sklep.7tdeg.mongodb.net/sklep?retryWrites=true&w=majority&appName=ecommerce
      database: sklep
      auto-index-creation: true
  
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  security:
    basic:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: false

logging:
  level:
    org.springframework.data.mongodb: INFO
    com.ecommerce: INFO
    org.mongodb.driver: WARN
